[package]
name = "pika-id"
version = "0.1.0"
edition = "2021"
readme="./README.md"
description="Pika ID implementation in Rust"
license = "MPL-2.0"

[dependencies]
base64 = "0.13.0"
mac_address = "1.1.3"
regex = "1.6.0"
rand = "0.8.5"
